### ISSUE TITLE
Have you successfully compiled Qt 6 on Ubuntu 18?

### ISSUE THREAD

**Issue by kero990** [techcaotri/ubuntu-18.04-build-qt6#1]
Hello, due to limitations with my embedded device, I can only use Ubuntu 18 or Debian 10. I'm glad to have come across this repository, as it has provided me with a lot of insights. However, I've been unable to successfully compile Qt 6, whether on Ubuntu 18 or Debian 10, whether your Docker setup or manually compiling it.

Currently, I'm stuck at 44% progress, with the error message:

```
error: no member named 'transform_reduce' in namespace 'std'
            QString details = std::transform_reduce(
                              ~~~~~^
```
This seems to require adding an include in GCC, but it appears that Clang and GCC behave differently.

If you have succeeded, could you provide me with some assistance? I would greatly appreciate it.

**Comment by techcaotri** [comment]
Hi @kero990, I've been quite busy lately and missed your message. I've never used Debian 10, however, I've successfully compiled Qt6 on Ubuntu 18.
From your error message, it seemed like you used a compiler different from clang-12, as in the `build_Qt_6_4_3.sh` script.
If you still need the Qt 6 for Ubuntu 18, I could send you the build artifact of Qt 6 for Ubuntu 18.

**Comment by kero990** [comment]
Oh sorry, I also missed your message.

In fact, I tried for a long time and tested many environment combinations, including configuring exactly according to the environment in your sh script. The reason for using Debian 10 instead of Ubuntu 18 is that many dependencies in the sh script seem to no longer be installable directly with apt, but Debian still can. I tried using the latest Clang, compiling the latest Qt6, and various environment combinations.

Additionally, my main focus is on using it on arm64 (only this is locked at no higher than Debian 10/Ubuntu 18 due to kernel reasons of the device). I guess yours is not arm64, so the build files are not very useful to me. I still hope to learn the entire compilation process.

I also tried using GitHub Actions to fully use your project, not just the environment, but they also got stuck during the process of installing some dependencies with apt.

I even posted on the Qt6 and Clang communities for help, but the advice they gave me was to upgrade the environment and compiler. I gave up for a while, thinking it was impossible to succeed. Hearing about your success really invigorated me.

**Comment by kero990** [comment]
I tried again to directly use your project, but it still failed. The issue lies with a few PPAs in your project that do not contain arm64 packages, so some apt commands would error out. This was the original reason for my switch to Debian 10, but there may still be differences in the environment that affect the outcome.

**Comment by techcaotri** [comment]
> I tried again to directly use your project, but it still failed. The issue lies with a few PPAs in your project that do not contain arm64 packages, so some apt commands would error out. This was the original reason for my switch to Debian 10, but there may still be differences in the environment that affect the outcome.

Yeah, missing packages or conflict version of packages are usually the causes of build failure. You could try to build those failed packages on your own, and try again. It's possible of it's still Ubuntu-based with the same version. I also usually do that for other projects.
